### ISSUE TITLE
評価指標は何か

### ISSUE THREAD

**Issue by chck** [no-free-lunch/torrent#1]
https://www.kaggle.com/c/dogs-vs-cats-redux-kernels-edition
![x](http://anchipachinco.up.n.seesaa.net/anchipachinco/image/jo1.jpg)

**Comment by sdual** [comment]
## 指標
- 犬である確率を計算し、ベルヌーイ分布のloglossが指標。  
https://www.kaggle.com/c/dogs-vs-cats-redux-kernels-edition#evaluation

**Comment by chck** [comment]
Done!!よくできました
